# Generated by Django 2.0.2 on 2018-03-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apptwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.EmailField(max_length=264)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Apptwo.User')),
            ],
        ),
    ]
