# Generated by Django 2.0.2 on 2018-04-07 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apptwo', '0003_auto_20180405_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='register',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
