# Generated by Django 2.0.2 on 2018-04-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
